# Generated by Django 4.2 on 2023-04-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_admin_login_client_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms_booked',
            old_name='guesthouse',
            new_name='hotel',
        ),
    ]
